name: Build Result

on:
  push:
    branches:
      - "main"
    paths:
      - "result/**"
      - ".github/workflows/call-docker-build-result.yaml"

  pull_request:
    branches:
      - "main"
    paths:
      - "result/**"
      - ".github/workflows/call-docker-build-result.yaml"

jobs:
  call-docker-build:
    name: Result Call Docker Build

    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main

    permissions:
      contents: read
      pull-requests: write

    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      # Enable DockerHub only
      dockerhub-enable: true
      ghcr-enable: false

      # IMPORTANT: must match your DockerHub repo
      image-names: |
        aarnav2/result

      # Tagging rules
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr

      # Folder containing Dockerfile
      context: result

      # Platforms to build
      platforms: linux/amd64
